### ISSUE TITLE
Click on Hour or Minute button triggers form action & some styling

### ISSUE THREAD

**Issue by KoljaL** [mskocik/svelty-picker#108]
Great component, thanks a lot :-)

Is it possible to add a preventDefault in here: `() => $$invalidate(5, isMinuteView = false)`

Styling:   
I use a global CSS and then the with of the table is a little to much and the tick-buttons getting a margin/padding.
So I had to reset it:

```css
.std-calendar-wrap {
	width: max-content !important;
}
button.sdt-tick {
	margin: 0;
	padding: 0;
}
```
